const REQUEST_FETCH_PRODUCTS = "REQUEST_FETCH_PRODUCTS";
const REQUEST_FETCH_SINGLE_PRODUCT = "REQUEST_FETCH_SINGLE_PRODUCT";
const PRODUCTS_FETCHED = "PRODUCTS_FETCHED";
const SINGLE_PRODUCT_FETCHED = "SINGLE_PRODUCT_FETCHED"
export {REQUEST_FETCH_PRODUCTS,REQUEST_FETCH_SINGLE_PRODUCT,PRODUCTS_FETCHED,SINGLE_PRODUCT_FETCHED};