const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const CLEAR_CART = "CLEAR_CART";
const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export {ADD_TO_CART,REMOVE_FROM_CART,CLEAR_CART,CHANGE_QUANTITY}