export const FETCH_USER = "FETCH_USER";
export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESSFULL = "REGISTRATION_SUCCESSFULL";
export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const CLEAR_REG_ERROR = "CLEAR_REG_ERROR";
export const CLEAR_REG_MESSAGE = "CLEAR_REG_MESSAGE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";


